3b1b/3Blue1Brown.com

README.md
These are the steps that Grant, Josh and myself followed to get the local Jekyll site running on our machines.
@vincerubinetti can you make sure we didn't do anything weird? so we don't run into trouble later. There are two commands in particular to look at.
When installing bundler we used the `user-install` flag rather than using `sudo`.
```sh
gem install --user-install bundler
```
After encountering an error when running `bundle install` we set the configuration to be local.
```sh
bundle config set --local path 'vendor/bundle'
```
I linked to resources I found online for troubleshooting errors. Also, for reference, I'm on a MacBook Pro running Catalina and the two other machines I think are the new M1 Macs.
=> Added OSX installation steps for local site to README.md

README.md, content/lessons/_index.md
- added getting started steps to README.md
- added cascading build option to lesson content type `content/lessons/_index.md`
@vincerubinetti please take a look at the build option. Its motivation is to prevent large resources from being synced to the bucket when they are used **only** as a source for compressed/processed versions of the resource. If the resource's `.RelPermalink` or `.Permalink` attribute is used in a template, it will still be included.
For example, say there is a large source image that gets processed in the build step, but is unused in the build directory.
```
example-lesson/
├── figure.png # large source image  5MB
└── index.md
```
After the build step, the processed images would be present, but the source image would not be and so it won't be synced to the bucket. …
=> Getting Started Steps and Build Option

components/Markdownify/index.js, components/Question/index.js, public/content/lessons/2017/256-bit-security/index.mdx, public/content/lessons/testbed-lesson.mdx
A few people ran into issues with math characters being incorrectly escaped. For example, the `\t` in `\times` was being converted to a tab character.
Experimenting more, I noticed that sometimes you have to write `\\times` and other times you have to write just `\times`. The problem is, React/JSX/MDX apparently parses `param="$4 \times 10^{40}$"` like a [raw string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw), without escaping any characters like `\n`, `\t`, etc., but parses `param={"$4 \times 10^{40}$"}` normally (as expected in javascript), escaping the characters.
Therefore, I've changed the `Question` component to once again take `choice1`, `choice2`, etc as inputs rather than an array, and all future components should be made to …
=> Fix math escape

.gitattributes, .github/workflows/sync-assets.yaml, components/Figure/index.js
Opening this pull request to preview and test the sync action.
Changes:
- Changed `.gitattributes` rules to reference `public/content/**/...` instead of `pages/lessons/**/...` after noticing lesson media files not managed by LFS.
- Added `dir` when building the bucket URL
- Excluded SVG file types from be prepended with bucket URL since they are served from Netlify
@3b1b I tested the production environment locally and things looked fine. Next step would be to merge into main and check the live site. As long as the `process.env.mode` is set to `production` it should work as intented.
=> Sync Action Update

components/Fade/index.js, components/LessonCard/index.js, components/LessonGallery/index.js, layouts/NormalLayout.js
Closes #115. Grant and I agreed that the fade made the site feel slow, but before removing it for sure I would like some feedback from others just to double check that this is a good change.
- Removes the fade effect from the lessons list
=> Remove fade effect from lessons list

components/LessonCard/index.js
- Adds a "video" icon to all lessons with an associated video (which is currently all of them)
- Change from a pencil icon to a newspaper for lessons with a text version available
- Closes #120
=> Add video icon, change text icon to newspaper

components/Clickable/index.module.scss, components/ContactForms/index.module.scss, components/Figure/index.js, components/PageContent/index.js, components/PiCreature/index.js, components/PiCreature/index.module.scss, components/Portrait/index.js, components/Portrait/index.module.scss, components/Section/index.js, components/Section/index.module.scss, public/content/contact.mdx, public/content/lessons/2017/256-bit-security/index.mdx, styles/theme.scss
- Adds a prop to `Section` called `width` that can either be `"normal"` or `"narrow"`
- Uses different `Section` widths in different parts of the site
- Passes the current width down to components which need to know it (`PiCreature` and `Portrait`) for their positioning.
- Closes #112
This PR is a bit spooky because the page width affects *everything*, so there are lots of little corners where things could break. But I've taken quite a bit of time to comb through all the uses of the `$page` width variable, as well as looking through different pages, and I *think* everything is good.
=> Make lessons narrower, everything else wider

components/Footnote/index.js, components/Footnote/index.module.scss, components/PageContent/index.js, public/content/lessons/testbed-lesson.mdx
- Creates an inline footnote component
- Manhandles the output of the MDX parser, which always just spits footnotes out at the bottom, to force them into their inline locations
=> Add inline footnotes

components/Accordion/index.js, components/Center/index.js, components/Chip/index.js, components/Clickable/index.js, components/FeatureCard/index.js, components/Figure/index.js, components/Footnote/index.js, components/FreeResponse/index.js, components/Header/index.js, components/HomepageFeaturedContent/index.js, components/Interactive/index.js, components/LessonCard/index.js, components/LessonGallery/index.js, components/LessonLink/index.js, components/LessonNav/index.js, components/Main/index.js, components/Markdownify/index.js, components/Patrons/index.js, components/PiCreature/index.js, components/Portrait/index.js, components/Question/index.js, components/Section/index.js, components/ShareButtons/index.js, components/Spoiler/index.js, components/Tooltip/index.js, components/TopicHeader/index.js, components/Twitter/index.js, package.json
This PR makes it so that if you use a component incorrectly (providing the wrong information, or not providing enough information), you will get an error in your browser's console describing what's wrong and how to fix it.
- Adds PropTypes to the vast majority of components
- Closes #99
=> Add PropTypes for components

components/Accordion/index.js, netlify.toml, next.config.js, public/content/contact.mdx
- Adds ids to the accordions on the FAQ/contact page so that old links keep working
- Adds a redirect from `/faq` to `/contact` so that old links keep working
- Closes #121
=> Add FAQ ids and redirect from `/faq` to `/contact`

public/content/lessons/2017/bitcoin/broadcast-transaction.mov, public/content/lessons/2017/bitcoin/broadcast-transaction.mp4, public/content/lessons/2017/bitcoin/charlie-leaves.mov, public/content/lessons/2017/bitcoin/charlie-leaves.mp4, public/content/lessons/2017/bitcoin/exchange-for-usd.mov, public/content/lessons/2017/bitcoin/exchange-for-usd.mp4, public/content/lessons/2017/bitcoin/guess-and-check.mov, public/content/lessons/2017/bitcoin/guess-and-check.mp4, public/content/lessons/2017/bitcoin/index.mdx, public/content/lessons/2017/bitcoin/miners.mov, public/content/lessons/2017/bitcoin/miners.mp4, public/content/lessons/2017/bitcoin/tally-up.mov, public/content/lessons/2017/bitcoin/tally-up.mp4
Got sloppy on the Bitcoin lesson. Need to replace all .mov files with .mp4. My bad!
=> Use .mp4 instead of .mov in Bitcoin lesson

components/LessonGallery/index.js, public/content/lessons/2017/backpropagation-calculus/index.mdx, public/content/lessons/2017/backpropagation/index.mdx, public/content/lessons/2017/gradient-descent/index.mdx, public/content/lessons/2017/neural-network-analysis/index.mdx, public/content/lessons/2017/neural-networks/index.mdx
- Slightly tweaks the search result ordering so that most results are reverse-chronological, but lessons in a series try their best to appear in a reasonable order, with probably an 85% success rate
- Makes neural networks a series with chapter numbers (rather than just a topic)
- Closes #189
=> Improve search result order of lessons in a series

components/Figure/index.js, next.config.js, package.json, util/pages.js, yarn.lock
- Gathers information about the dimensions of images at build time
- Uses that information to help the `Figure` component size it self correctly even before the images load in, which prevents the page from changing size while scrolling, which helps the table of contents links to always land you in the correct place
=> Size figures instantly to fix table of contents scrolling bug

public/content/lessons/2017/essence-of-calculus/index.mdx
- fixes a small typo in Essence of Calculus Ch.1: 
"function evaluated at 3.001 and evaluated 3" ->
"function evaluated at 3.001 and evaluated *at* 3"
=> Fix small typo in Essence of Calculus Ch.1

public/content/lessons/2016/inverse-matrices/index.mdx
- There were two cases of "one another" being written as "one and other".
- Fixes two minor errors where "one another" was instead written as "one and other". 
In the following two paragraphs: 
> These variables could be voltages across various elements in a circuit, prices of certain stocks, parameters in a machine learning network, really any situation where you might be dealing with multiple unknown numbers that somehow depend on ~**one and other**~ one another.
> How exactly they depend on each other is determined by the substance of your science, whether that means modeling the physics of circuits, the dynamics of the economy, or interactions in a neural network, but often you end up with a list of equations which relate these …
=> Fix typo in inverse-matrices lesson

public/content/index.mdx, public/content/lessons/2022/visual-proofs/index.mdx, public/content/lessons/2022/visual-proofs/patrons.txt
- Publishes the lesson corresponding to the latest video: How to lie with visual proofs
- Replaces the first featured content item, previously the subsets animation, with the visual proofs lesson
=> Publish visual proofs lesson

public/content/lessons/2019/windmills/index.mdx
Fixed Typo. Changed no to now in quiz.
-changes  public/content/lessons/2019/windmills/index.mdx
-fixed typo 'no' to 'now' in quiz
=> Fixed Typo

layouts/LessonLayout.js
- fixes the capitalization of "GitHub"
=> fix capitalization of GitHub

public/content/lessons/2017/gradient-descent/index.mdx
This pull request fixes a typo in one of the Figures in gradient-descent/index.mdx, which currently prevents the gradient-nudge-weights.mp4 video from playing on https://www.3blue1brown.com/lessons/gradient-descent.
=> Gradient Descent lesson: fix weight nudge video link

util/locale.js
- Fixes #306 
- There was a off by 1 error happening with publishing dates across all lessons due to the UTC vs local timezone formatting
- Now the date posted in the public folder matches the date on the website
=> add localdate to account for utc offset in publishing dates

next.config.js
- Fixes #367 
- adds an images field in the config with an empty path to allow for relative images to pull from `BASE_URL/images/**/*` instead of `/images/**/*`
- Cannot be verified in dev, since dev continues to showcase the same behavior, needs to be pushed and built to check production
- I have implemented this change across some other frontend websites in the past and it has solved
=> Display Images In Production

public/content/lessons/2017/eulers-number/index.mdx
-fixes the order of the footnotes in Calculus Chapter 6
Sorry if I've not done this correctly. I'm not very experienced with Github.
=> Fixing the order of the footnotes in Calculus Chapter 6

public/content/lessons/2017/implicit-differentiation/index.mdx
-changed a reference to something being mentioned in a "footnote video" to it being mentioned in a "previous lesson" as the text adaption of the video in question is treated no differently from any other text adaption, hence making this reference a little odd.
=> Changing reference to "footnote video" to "previous lesson"

LICENSE.md, public/LICENSE.md
Add a dual license for which the underlying tooling (including react components, etc) is open source, but the blog post content is not.
=> Add licenses

components/AboutPageGallery/index.js, components/AboutPageGallery/index.module.scss, data/credits.yaml, data/teamMemberData.js
- Updates `credits.yaml` to contain valid links to contributors in the "about" page when navigating from a lesson
- Adds padding to the top of team member cards so there is some breathing room when navigating to a team contributor's info. For example, when navigating to: `https://www.3blue1brown.com/about#james-schloss`.
- Updates Kurt's social links
Notes:
The `credits.yaml` file could probably be removed entirely, but it would require modifying some logic in `components/LessonDetails/index.js`.
=> Fix broken lesson contributor links

data/topics.yaml
- Removes the Essence of Linear Algebra Preview lesson from the series overview
=> Remove EOA preview lessons

data/topics.yaml
- Removes a phantom lesson "derivative-formulas-geometrically" from `topics.yaml`
- Currently, when on the [derivatives](https://www.3blue1brown.com/lessons/derivatives) lesson, there is no link to the next lesson at the end of the chapter. Also, if you press the next arrow in the video carousel you get a page not found error.
=> Fix Essence of Calculus Navigation

public/content/lessons/2016/matrix-multiplication/index.mdx
- Replaces the word "communitive" with the word "commutative" in the lesson on [https://www.3blue1brown.com/lessons/matrix-multiplication](matrix multiplication)
=> Communitive -> commutative
