- .github/pull_request_template.md
- components/Clickable/index.js
- components/LessonCard/index.js
- components/LessonCard/index.module.scss
- components/LessonGallery/index.module.scss
- components/LessonLink/index.js
- components/LessonNav/index.module.scss
- components/Patrons/index.js
- components/PiCreature/index.module.scss
- components/Question/index.js
- components/TableOfContents/index.js
- public/content/index.mdx
- util/math.js
closes #84 
roughly in order of diff:
- fix clickable link not being passed through bug
- make lesson card images bigger, crop to 16:9 since youtube provides 4:3 with letterboxes
- fix date not showing bug in lesson card
- various css tweaks
- fix patrons component. react-hooks lint issue, other tweaks
- change pi creatures to be on right by default to lesson likelihood of being overlapped by table of contents
- make question component explanation param optional
- fix small pixel bug with table of contents where clicking on an entry doesn't scroll it far enough into view to make it active
- greatly reduce screen width breakpoint of table of contents showing up automatically
- fix misuse bug of seedrandom
> various fixes

- components/Question/index.js
- public/content/lessons/2016/inscribed-rectangle-problem/index.mdx
- public/content/lessons/2017/256-bit-security/index.mdx
- public/content/lessons/2017/derivatives/index.mdx
- public/content/lessons/2017/essence-of-calculus/index.mdx
- public/content/lessons/2017/neural-networks/index.mdx
- public/content/lessons/2019/eulers-formula-dynamically/index.mdx
- public/content/lessons/testbed-lesson.mdx
- Changes the question component to use children (the inner content) as the explanation rather than a separate "explanation" prop
> Question component: Use children as explanation

- components/Clickable/index.module.scss
- components/Question/index.js
- Disables the "check answer" button when no answer is selected
- Actually resets the selected answer when the reset button is pressed
- Closes #122
> Fix question behavior when no answer selected

- components/LessonGallery/index.js
- components/LessonGallery/index.module.scss
- components/Section/index.js
- components/TopicHeader/index.js
- components/TopicHeader/index.module.scss
- data/topics.yaml
- pages/_app.js
- pages/topics/[slug].js
- util/pages.js
- util/string.js
- Creates individual pages for each topic
- Changes the topic grid of the lessons page to link to each topic page (rather than displaying everything inline)
- Closes #111
Design is hard. 😅 Getting the header images to look decent was a real challenge. I'm still not totally satisfied, but this is the best I've got. Feedback welcome!
> Topic pages

- components/LessonCard/index.js
- Removes the "video" icon from the lesson cards
- Closes #137
> Remove video icons

- public/content/lessons/2019/windmills/index.mdx
> Patching windmill articles

- components/ShareButtons/index.js
- components/ShareButtons/index.module.scss
- components/SocialIcons/index.module.scss
- layouts/LessonLayout.js
- Adds share buttons and social links to the bottom of lesson pages
- Closes #144
> Add share buttons to lessons

- components/LessonGallery/index.js
- components/LessonGallery/index.module.scss
- components/PiCreature/index.module.scss
- Adds a nicer screen with a pi creature and google link when there are no search results
- Closes #165
> Add better no search results message

- components/Figure/index.module.scss
- Changes captions to not be italic
- Closes #110
> Change caption style

- _redirects
- netlify.toml
- public/content/lessons/2017/three-utilities/patrons.txt
- public/content/lessons/2019/cramers-rule/patrons.txt
> Bring over redirects from old site

- components/TableOfContents/index.js
> Fix ToC markdown in header bug

- components/TableOfContents/index.js
> Bug fix: update ToC on client-side route change

- components/TableOfContents/index.js
- Fixes an error when the table of contents can't find an element it's looking for
> Fix ToC error

- components/PiCreature/index.module.scss
- Changes pi creatures to position themselves in a smarter way (see #181)
- Fixes a bug where two media queries were set up for `width < x` and `width > x` but failed on `width = x`
- Closes #181
> Improve pi creature positioning

- layouts/LessonLayout.js
- Adds a link to each lesson to submit a correction on Github
> Add "submit a correction" link

- _redirects
Adds domain redirects for various aliases of 3blue1brown.com
> Domain redirects

- next.config.js
- package.json
- sentry.client.config.js
- sentry.properties
- sentry.server.config.js
- yarn.lock
> Add sentry

- .github/actions/sync/entrypoint.sh
- Changes the sync logic to sync all image/video assets in the public directory
> Change sync logic

- public/content/lessons/2017/essence-of-calculus/index.mdx
- Updates the footnotes in the first chapter of the calculus series to use the footnote component.
> Essence of calculus chapter 1 footnotes

- components/Announcement/index.js
- components/Announcement/index.module.scss
- components/index.js
- public/content/index.mdx
- Creates an `Announcement` component
- Uses the new component to announce SoME1 on the home page
> Create SOmE1 announcement

- public/content/lessons/2017/essence-of-calculus/index.mdx
- videa -> video
- it's -> its
- us using -> our using
> Grammar changes

- components/LessonCard/index.js
- components/LessonVideo/index.js
- components/LessonVideo/index.module.scss
- data/lesson-redirects.yaml
- Allows some lesson slugs to redirect to external sites
- Makes sure the next/prev buttons next to videos show regardless of whether the video is in a series.
> Custom lesson links

- public/content/lessons/2017/backpropagation/index.mdx
Fixes spelling errors => On line 126, `incrase` should be `increase` and on lines 127, 128, 129 and 130 `neroun` should be `neuron`
> fixed spell errors

- public/content/lessons/2017/bitcoin/index.mdx
- Changes "blieves" to "believes" on line 518
> Fix spelling mistake

- public/content/lessons/2017/derivatives-power-rule/index.mdx
- public/content/lessons/2017/essence-of-calculus/index.mdx
> Fix typos and grammar

- components/Graph/index.js
- components/Interactive/index.js
- pages/app/newtons-fractal.js
- public/content/lessons/2021/newtons-fractal/index.mdx
- public/content/lessons/2021/newtons-fractal/newtons-fractal-interactive/index.js
- public/content/lessons/2021/newtons-fractal/newtons-fractal-interactive/index.module.scss
*This is still a work-in-progress. I need to make sure the code isn't ugly.*
**Preview:** https://deploy-preview-279--3blue1brown.netlify.app/lessons/newtons-fractal
- Creates a new page for the Newton's Fractal interactive
> Create "Newton's Fractal" interactive page

- public/content/lessons/2016/linear-transformations/index.mdx
1. Fixes minor typo in linear transformation section.
2. Fixes i_hat vector w.r.t. comment by Harry Zhang on the lesson site.
-
-
-
> Update index.mdx - Essence of Linear Algebra, Chapter 3 Linear transformations and matrices

- public/content/lessons/2017/essence-of-calculus/index.mdx
> Fixed a formula error

- components/SocialIcons/index.js
- data/topics.yaml
- public/content/index.mdx
- public/content/lessons/2022/wordle2/index.mdx
- public/content/lessons/2022/wordle2/patrons.txt
- Adds second wordle video
- Updates social icons
> Home page updates

- data/topics.yaml
- public/content/lessons/2022/convolutions/index.mdx
- public/content/lessons/2022/convolutions/patrons.txt
Adding https://youtu.be/KuXjwB4LzSA to the website
> Added convolutions lesson

- .github/workflows/sync-assets.yaml
This pull request updates the ubuntu linux machine version and checkout version in the sync assets action.
> Update versions for sync-assets action

- public/content/lessons/2017/backpropagation-calculus/index.mdx
> Small grammatical fix to index.mdx

- public/content/lessons/2017/taylor-series/index.mdx
In the last question, you have the answer as "1 + ...", it should be "x + ...". The graphics do show the correct formula.
-
-
-
> noticed a mistake

- data/site.yaml
This may possibly fix why all images currently don't load
> Remove trailing / from bucket url

- public/content/lessons/2017/essence-of-calculus/index.mdx
The note should clarify that it's talking about the still figure, not the animated figure.
- Clarifies that the note is referring to the still figure, not the animation.
> Clarify that the note is about the still figure

- public/content/lessons/2017/eulers-number/index.mdx
-fixing a small typo of "the the" to "to the"
Sorry for submitting 2 pull requests to the same file in quick succession. I noticed these issues only as I was reading the lesson and submitted these pull requests as soon as I saw them.
> Fixing small typo in Calculus Chapter 6

- public/content/lessons/2017/chain-rule-and-product-rule/index.mdx
-Removes areference to the next lesson being about connected rates of change as this is not the next lesson, the next lesson actually being about e.
> Removing an incorrect reference to the content of the next lesson.

- util/transformSrc.js
Reverts 3b1b/3Blue1Brown.com#389
> Revert "Fix image bug"

- public/content/about.mdx
Reverts 3b1b/3Blue1Brown.com#392
> Revert "Update about page"

- public/content/lessons/2016/span/index.mdx
- edits grammar in 1 line
- adds believed missing word in another line
-
> grammatical suggestions to linear algebra lesson 2

- public/content/lessons/2016/dot-products/index.mdx
- Correct dot product example calculation result
> Correct dot product example calculation result

- public/content/lessons/2016/eigenvalues/index.mdx
- Fixes a typo in question 2 in eigenvalue lecture
> «There are NO real eigenvalues»

- public/content/lessons/2016/3d-transformations/index.mdx
- removes duplicate occurrence of the word "about"
> remove duplicate occurrence of "about"

- public/content/lessons/2016/change-of-basis/index.mdx
the fourth vector should be [−2/3 -1/3 ]^T
-
-
-
> correct a typo in line 398

- public/content/lessons/2019/cramers-rule/index.mdx
were was previously used instead of where
> fixed typo in index.mdx

- public/content/lessons/2016/change-of-basis/index.mdx
- removes a duplicate phrase in chapter 13 of the essence of linear algebra course: replaced "square grid square grid" with "square grid"
-
> removed duplicate words

- public/content/lessons/2016/dot-products/index.mdx
- Replaced “ijhat” with “i-hat”
-
-
> Corrected typo: Replaced “ijhat” with “i-hat”

- public/content/lessons/2016/vectors/index.mdx
- [ X] I have requested a review from the appropriate persons
- [X ] I have checked that my changes work in the preview
- [ X] I have checked that the rest of the site is still functioning in the preview
- [ X] I have checked that my content/code is consistent with existing content/code
- [ X] I have used components in the places and ways they are intended (see the readme)
- [ X] I have formatted all of my code with Prettier
- Fixes a grammatical typo
-
-
> Fixed typo

- public/content/lessons/2016/change-of-basis/index.mdx
Fixed a typo in an example. Changed: "How would be translate the vector" to "How would we translate the vector"
> Fixed a small typo.

- .gitignore
- components/FeaturedVideo/index.js
- components/HomepageFeaturedContent/index.js
- components/LessonCard/index.js
- components/LessonCard/index.module.scss
- components/LessonGallery/index.js
- components/LessonGallery/index.module.scss
- pages/_app.js
- public/content/lessons/2025/transformers-talk/index.mdx
- util/featuredVideoContext.js
Change the effect of clicking lesson cards to play the video on the home page, rather than jumping to the alternate lesson page.
> Default to playing videos on home page

- public/content/lessons/2017/derivatives-power-rule/index.mdx
Removed redundant sentences and fixed a typo
-
-
-
> Update index.mdx for "Power Rule through geometry"
